[[CURRENCIES]]
code="Blocklynk"
issuer="GDH6OP5BIVSMQHHYS37J7YLNSOJF5MEOLRNGUY3BHDHRKDI37LN6CNYX"
name="ZainDev0"
desc="Blocklynk is a fully decentralize and real utility project"
image="https://zainulaabdeen.com/assets/profile-back-CWDqEaCs.webp"
