[[CURRENCIES]]
code="Blocklynk"
issuer="GC4V7FY5GACQT2NGULYBTO6CSXVXAC6WJNEZLDWRFYFR5FMOSKSCO66I"
name="ZainDev0"
desc="Blocklynk is a Fully decentralize and real utility project"
image="https://zainulaabdeen.com/assets/profile-back-CWDqEaCs.webp"