[[CURRENCIES]]
code="Blocklynk"
issuer="GDH6OP5BIVSMQHHYS37J7YLNSOJF5MEOLRNGUY3BHDHRKDI37LN6CNYX"
name="ZainDev0"
desc="Blocklynk is a Fully decentralize and real utility project"
image="https://image2url.com/r2/default/images/1773768175954-ffe39871-8ebe-467e-8fe0-6a566b6161a2.png"
